name: Pipeline

on:
  pull_request:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Deploy no EC2 -AWS
      run: |
            echo "Conectando no EC2"
            echo "${{secrets.RESTORAN_CHAVE}}" > private_key && chmod 600 private_key
            ssh -o StrictHostKeyChecking=no -i private_key ubuntu@ec2-3-215-172-96.compute-1.amazonaws.com "
                   cd restoran_100/;git pull;./start index.html"
